---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /opt/homebrew/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: naitik1/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker create -it -d --name calculator naitik1/calculator